name: 🗃️ Data Platform Epic
description: Creates a Data Platform Epic
title: "[gitmoji] <title>"
labels: ["Epic"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the fields below.
  - type: textarea
    id: describe-epic
    attributes:
      label: Brief summary of what this Epic is
      placeholder: "This Epic..."
  - type: textarea
    id: list-issues
    attributes:
      description: Add issues by using hash then issue number
      contact_links:
      value: "- [ ] #1
      
               - [ ] #2 "
    validations:
      required: false
      label: List issues in this epic
  - type: textarea
    id: other-info
    attributes:
      description: Other information
      label: Other information
      value:
        Slack channel = #data-platform-epic-name
    validations:
      required: false
contact_links:
  - name: Task list to issues
    url: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#about-issue-task-lists
    about: Information about working with tasks
